### ISSUE TITLE
to be deleted

### ISSUE THREAD

**Issue by zilexa** [fmoledina/snapraid-btrfs-runner#1]
nvm, already figured it out.

**Comment by fmoledina** [comment]
Hello @zilexa

Sorry I missed this chain. That r/datahoarder post is quite old and refers to a previous attempt of mine to set up snapraid-btrfs-runner. My thought process now has been detailed out at the [selfhosted.show wiki](https://wiki.selfhosted.show/tools/snapraid-btrfs/) Hope this helps!

I'll have a look at the other issues that you have raised. Thanks!
