### ISSUE TITLE
Why specify snapper configs? snapraid-btrfs finds them automatically

### ISSUE THREAD

**Issue by zilexa** [fmoledina/snapraid-btrfs-runner#2]
```
; specify snapper-configs and/or snapper-configs-file as specified in snapraid-btrfs; only one instance of each can be specified in this config
snapper-configs = 
snapper-configs-file =
```
It is unclear to me why the script needs this. 
Snapraid-btrfs finds the configs in /etc/snapper/configs. I have 3 configs there representing subvolumes on 3 disks.

**Comment by fmoledina** [comment]
The script does not require these config items. They map directly onto the `--snapper-configs` and `--snapper-configs-file` options for `snapraid-btrfs`. If they are not specified in the config, then `snapraid-btrfs` finds the Snapper configs exactly as you indicate. 

I can indicate that these are optional in the comment to make that more clear.

**Comment by zilexa** [comment]
Thanks, indeed I tested without filling in those params and it works :)
