### ISSUE TITLE
Option to only email if there was no successful error-free run

### ISSUE THREAD

**Issue by zilexa** [fmoledina/snapraid-btrfs-runner#3]
Not sure how/if this is possible, but it would be a nice to have to only sent email if there is anything to report. 
If no email is received, it means it ran well.

**Comment by fmoledina** [comment]
This is a great feature idea. I'll look at upstream snapraid-runner to see if others have suggested it there and see how best to implement it here.

**Comment by blakedewey** [comment]
This should be possible by changing the `sendon` option of the `email` section of the config file. If you change it to just `error`, then it should do exactly this (only send an email if the process doesn't succeed).

**Comment by fmoledina** [comment]
@blakedewey, thanks for pointing that out. Yes, it appears that this functionality is in there and was ported from the upstream snapraid-runner project. Closing this issue. Thanks!
