### ISSUE TITLE
Detecting executables

### ISSUE THREAD

**Issue by dli7319** [fmoledina/snapraid-btrfs-runner#6]
Can we use `shutil.which` instead of `os.path.isfile` for detecting executables? \
This has the advantage of looking through the PATH so that we don't need absolute paths but works either way. \
If `snapper`, `snapraid-btrfs`, and `snapraid` are in PATH, these would no longer need to be changed in the config.

**Comment by fmoledina** [comment]
Hello! I'm open to that concept, although I don't have time to implement it for the near future. Also, some folks may still want to specify executables in the config depending on how they installed snapraid and snapper. I'll leave this issue open and let it simmer for a bit. Thanks!

**Comment by dli7319** [comment]
The implementation is pretty simple (see PR) and does not change anything for existing users. \
For new users, `shutil.which` also has the benefit of returning false for non-executable files.

**Comment by fmoledina** [comment]
Implemented PR #7. Thank you!
